status: "ready"
context:
  id: "choice"
  name: "choice"
  label: "I agree with the Shipping and Billing terms and conditions conditions conditions conditions conditions conditions conditions conditions conditions conditions conditions"
  value: "1"
  required: false
  disabled: false
  checked: false
  error: "Please provide a value for this field"
default: "default-light"
variants:
  - name: "default-light"
  - name: "default-dark"
    preview: "@dark"
notes: "This component is based on 'checkbox material like' and inherits its behavior"
