title: "Radio"
status: "ready"
context:
  id: "choice"
  name: "choice"
  label: "Some condition"
  value: "1"
  required: false
  disabled: false
  checked: false
  error: "Please provide a value for this field"
default: "default-black"
variants:
  - name: "default-black"
  - name: "default-white"
    preview: "@dark"
