language: node_js
node_js:
  - "8"
before_script:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:fontforge/fontforge --yes
  - sudo apt-get update -qq
  - sudo apt-get install fontforge
script:
  - npm run build
after_success:
  - npm run deploy
