status: "ready"
context:
  id: "select"
  name: "select"
  label: "Text"
  required: false
  disabled: false
  # selected accepts either false or a number starting with 1 that indicates
  # the option index
  selected: false
  options:
    - "Long long option Long long option Long long option Long long option Long long option Long long option Long long option Long long option"
    - "option 2"
    - "option 3"
    - "option 4"
    - "option 5"
    - "option 6"
    - "option 7"
    - "option 8"
    - "option 9"
    - "option 10"
    - "option 11"
    - "option 12"
    - "option 13"
    - "option 14"
    - "option 15"
default: "light"
variants:
  - name: "light"
    context:
      error: ""
  - name: "dark"
    preview: "@dark"
    context:
      error: ""
  - name: "with-helper-light"
    context:
      error: ""
      helper: "Please note that this form field has a helper text"
  - name: "with-helper-dark"
    preview: "@dark"
    context:
      error: ""
      helper: "Please note that this form field has a helper text"
  - name: "with-error-light"
    context:
      error: "Please provide a value for this field"
      helper: ""
  - name: "with-error-dark"
    preview: "@dark"
    context:
      error: "Please provide a value for this field"
      helper: ""
  - name: "with-error-and-helper-light"
    context:
      error: "Please provide a value for this field"
      helper: "Please note that this form field has a helper text"
  - name: "with-error-and-helper-dark"
    preview: "@dark"
    context:
      error: "Please provide a value for this field"
      helper: "Please note that this form field has a helper text"
