status: "ready"
context:
  id: "choice"
  name: "choice"
  label: "I agree with the Shipping and Billing terms and conditions conditions conditions conditions conditions conditions conditions conditions conditions conditions conditions"
  value: "1"
  required: false
  disabled: false
  checked: false
default: "light"
variants:
  - name: "light"
    context:
      error: ""
  - name: "dark"
    preview: "@dark"
    context:
      error: ""
      label: "I agree with the Shipping and Billing terms"
  - name: "with-helper-light"
    context:
      error: ""
      helper: "Please note that this form field has a helper text"
  - name: "with-helper-dark"
    preview: "@dark"
    context:
      error: ""
      helper: "Please note that this form field has a helper text"
  - name: "with-error-light"
    context:
      error: "Please provide a value for this field"
      helper: ""
  - name: "with-error-dark"
    preview: "@dark"
    context:
      error: "Please provide a value for this field"
      helper: ""
  - name: "with-error-and-helper-light"
    context:
      error: "Please provide a value for this field"
      helper: "Please note that this form field has a helper text"
  - name: "with-error-and-helper-dark"
    preview: "@dark"
    context:
      error: "Please provide a value for this field"
      helper: "Please note that this form field has a helper text"
