status: "ready"
context:
  id: "text"
  name: "text"
  label: "Text"
  required: false
  value: ""
  disabled: false
  # Any text format, no checkbox/radio:
  type: "text"
  autocomplete: ""
default: "light"
variants:
  - name: "light"
    context:
      error: ""
      helper: ""
  - name: "dark"
    preview: "@dark"
    context:
      error: ""
      helper: ""
  - name: "with-helper-light"
    context:
      error: ""
      helper: "Please note that this form field has a helper text"
  - name: "with-helper-dark"
    preview: "@dark"
    context:
      error: ""
      helper: "Please note that this form field has a helper text"
  - name: "with-error-light"
    context:
      error: "Please provide a value for this field"
      helper: ""
  - name: "with-error-dark"
    preview: "@dark"
    context:
      error: "Please provide a value for this field"
      helper: ""
  - name: "with-error-and-helper-light"
    context:
      error: "Please provide a value for this field"
      helper: "Please note that this form field has a helper text"
  - name: "with-error-and-helper-dark"
    preview: "@dark"
    context:
      error: "Please provide a value for this field"
      helper: "Please note that this form field has a helper text"
